server:
  port: 8089
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/es_test?useSSL=false
    username: root
    password: dujiafeng
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    elasticsearch:
      repositories:
        enabled: true
  elasticsearch:
    uris: localhost:9200

logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: HH:mm:ss:SSS
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: cn.gyyx.cabinet.pojo